import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Section from "@/components/Section";
import { useState } from "react";
import { BiDownArrow, BiUpArrow } from "react-icons/bi";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isAboutMeOpen, setIsAboutMeOpen] = useState(false);
  const [isSkillsOpen, setIsSkillsOpen] = useState(false);
  return (
    <>
      <Head>
        <title>MK Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='snap-y snap-promixity h-screen w-screen overflow-scroll scrollbar-hide'>
        <Navbar />
        <Section id='sec1' color='bg-slate-900' size='none'>
          <div className='relative border-b-4 border-slate-900 shadow-xl'>
            <div className='absolute w-full h-full top-[30%]'>
              <div className='flex flex-col items-center'>
                <div className='flex w-52 h-52 border-2 border-slate-500 rounded-full items-center justify-center shadow bg-slate-800'>
                  <div className='relative w-full h-full rounded-full overflow-hidden'>
                    <Image
                      src='/profile.jpg'
                      alt='profile image'
                      fill
                      priority
                    />
                  </div>
                </div>
                <h1
                  className={`${inter.className} text-center font-bold text-4xl text-slate-300`}
                >
                  Matthew Krain
                </h1>
                <h2
                  className={`${inter.className} text-center font-bold text-xl text-green-300`}
                >
                  Full Stack Engineer
                </h2>
              </div>
            </div>
            <div className='absolute top-20 left-20 z-10'>
              <button
                className='cursor-pointer flex flex-row gap-x-1'
                onClick={() => setIsAboutMeOpen(!isAboutMeOpen)}
              >
                <h2
                  className={`${inter.className} select-none text-green-200 active:text-green-100`}
                >
                  About Me
                </h2>
                {!isAboutMeOpen ? (
                  <BiDownArrow className='mt-1 text-green-400' />
                ) : (
                  <BiUpArrow className='mt-1 text-red-400' />
                )}
              </button>

              {isAboutMeOpen && (
                <div className='w-[50%]'>
                  <p
                    className={`${inter.className} text-sm text-slate-300 select-none bg-slate-800 p-2 rounded-2xl border-2 border-green-300`}
                  >
                    Full Stack Engineer with 3 years of experience in developing
                    automation software and digital processes for the Chemical
                    Manufacturing industry. Proficient in JavaScript/TypeScript
                    with experience in React and React Native. Adept at working
                    in fast-paced, collaborative environments and continuously
                    seeking new knowledge, particularly in the area of Machine
                    Learning Models. Proven ability to lead technical teams and
                    produce software solutions that yield multi million-dollar
                    savings for a Fortune 500 company.
                  </p>
                </div>
              )}
            </div>
            <div className='absolute bottom-20 right-20 z-10'>
              {isSkillsOpen && (
                <div className='flex flex-col gap-y-2 mt-6'>
                  <div
                    className={`${inter.className} text-sm text-slate-300 select-none bg-slate-800 p-2 rounded-2xl border-2 border-green-600`}
                  >
                    <div className='flex flex-row gap-x-2'>
                      <h3 className='text-slate-200 underline decoration-2'>
                        Languages ::
                      </h3>
                      <p> JavaScript, TypeScript, HTML, CSS, Python, C#, VBA</p>
                    </div>
                  </div>
                  <div
                    className={`${inter.className} text-sm text-slate-300 select-none bg-slate-800 p-2 rounded-2xl border-2 border-green-500`}
                  >
                    <div className='flex flex-row gap-x-2'>
                      <h3 className='text-slate-200 underline decoration-2'>
                        Framework/Libraries ::
                      </h3>
                      <p> React, Node.js, Express, TailwindCSS, SST, Jest</p>
                    </div>
                  </div>

                  <div
                    className={`${inter.className} text-sm text-slate-300 select-none bg-slate-800 p-2 rounded-2xl border-2 border-green-400`}
                  >
                    <div className='flex flex-row gap-x-2'>
                      <h3 className='text-slate-200 underline decoration-2'>
                        Leadership ::
                      </h3>
                      <p>
                        SAP & Production Team Leader, C.I. Site Leader for
                        Safety and Sustainability, Training
                        Developer/Coordinator
                      </p>
                    </div>
                  </div>
                  <div
                    className={`${inter.className} text-sm text-slate-300 select-none bg-slate-800 p-2 rounded-2xl border-2 border-green-300`}
                  >
                    <div className='flex flex-row gap-x-2'>
                      <h3 className='text-slate-200 underline decoration-2'>
                        Communication ::
                      </h3>
                      <p>
                        Ecolab Global Sustainability Presenter, Site Safety
                        Trainer
                      </p>
                    </div>
                  </div>
                </div>
              )}
              <div className='absolute right-0'>
                <button
                  className='cursor-pointer flex flex-row gap-x-1'
                  onClick={() => setIsSkillsOpen(!isSkillsOpen)}
                >
                  <h2
                    className={`${inter.className} select-none text-green-200 active:text-green-100`}
                  >
                    Skills
                  </h2>
                  {!isSkillsOpen ? (
                    <BiDownArrow className='mt-1 text-green-400' />
                  ) : (
                    <BiUpArrow className='mt-1 text-red-400' />
                  )}
                </button>
              </div>
            </div>
            <video className='z-0' autoPlay loop muted>
              <source src='/intro2.mp4' />
            </video>
          </div>
          {/*
          <div className='bg-slate-800 w-screen pt-20 pb-10 shadow-lg'>
            
            <div className='m-auto flex w-24 h-24 border-2 rounded-full items-center justify-center shadow'>
              <p className='text-center text-slate-200'>Profile</p>
            </div>
            <h1
              className={`${inter.className} text-center font-bold text-4xl text-slate-300 select-all`}
            >
              Matthew Krain
            </h1>
            <h2
              className={`${inter.className} font-bold text-center text-sky-300`}
            >
              Full Stack Developer
            </h2>
            <p
              className={`${inter.className} text-center text-sm text-slate-400`}
            ></p>
          </div>

          <div className='flex flex-col w-[80%] justify-evenly gap-y-20 p-4'>
            <div className=''>
              <h2 className={`${inter.className}`}>About Me</h2>
              <p className={`${inter.className} text-md text-slate-200`}>
                Full Stack Engineer with 3 years of experience in developing
                automation software and digital processes for the Chemical
                Manufacturing industry. Proficient in JavaScript/TypeScript with
                experience in React and React Native. Adept at working in
                fast-paced, collaborative environments and continuously seeking
                new knowledge, particularly in the area of Machine Learning
                Models. Proven ability to lead technical teams and produce
                software solutions that yield multi million-dollar savings for a
                Fortune 500 company.
              </p>
            </div>
            <div className={`${inter.className}`}>
              <h2>Skills</h2>
              <div className='flex flex-row gap-x-2'>
                <h3
                  className='text-slate-200 underline decoration-2
                '
                >
                  Languages ::
                </h3>
                <p> JavaScript, TypeScript, HTML, CSS, Python, C#, VBA</p>
              </div>
              <div className='flex flex-row gap-x-2'>
                <h3 className='text-slate-200 underline decoration-2'>
                  Framework/Libraries ::
                </h3>
                <p> React, Node.js, Express, TailwindCSS, SST, Jest</p>
              </div>
              <div className='flex flex-row gap-x-2'>
                <h3 className='text-slate-200 underline decoration-2'>
                  Leadership ::
                </h3>
                <p>
                  SAP & Production Team Leader, C.I. Site Leader for Safety and
                  Sustainability, Training Developer/Coordinator
                </p>
              </div>
              <div className='flex flex-row gap-x-2'>
                <h3 className='text-slate-200 underline decoration-2'>
                  Communication ::
                </h3>
                <p>
                  Ecolab Global Sustainability Presenter, Site Safety Trainer
                </p>
              </div>
           </div>
          </div>*/}
        </Section>

        <Section id='sec2' color='bg-sky-200'>
          <div className='bg-slate-900 w-screen pt-20 pb-10 shadow-lg mb-4'>
            <h1
              className={`${inter.className} text-center font-bold text-4xl text-slate-300`}
            >
              Blog
            </h1>
          </div>
        </Section>
        <Section id='sec3' color='bg-slate-900'>
          <div className='bg-slate-900 w-screen pt-20 pb-10 shadow-lg'>
            <h1
              className={`${inter.className} text-center font-bold text-4xl text-slate-300`}
            >
              Projects
            </h1>
          </div>
          <div className='flex flex-row snap-x snap-mandatory w-[50%] h-full px-28 overflow-scroll scrollbar-hide border-4'>
            <div className='border'>
              <h2>Kit</h2>
            </div>
            <div className='border'>
              <h2>Chuddies</h2>
            </div>
          </div>
        </Section>
        <Section id='sec4' color='bg-red-200'>
          <div className='bg-slate-900 w-screen pt-20 pb-10 shadow-lg mb-'>
            <h1
              className={`${inter.className} text-center font-bold text-4xl text-slate-300`}
            >
              Contact Me
            </h1>
          </div>
          <div className='w-full h-full relative'>
            <Image src='/laptopRGB.jpg' alt='laptop' fill priority />
          </div>
        </Section>
      </main>
    </>
  );
}
