import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Section from "@/components/containers/Section";
import { useState } from "react";
import { BiDownArrow, BiUpArrow } from "react-icons/bi";
import BlogLink from "@/components/containers/BlogLink";
import GridContainer from "@/components/containers/GridContainer";
import ProjectContainer from "@/components/containers/ProjectContainer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isAboutMeOpen, setIsAboutMeOpen] = useState(false);
  const [isSkillsOpen, setIsSkillsOpen] = useState(false);

  const [isKnockExpanded, setIsKnockExpanded] = useState(false);
  const [isChuddiesExpanded, setIsChuddiesExpanded] = useState(false);
  return (
    <>
      <Head>
        <title>MK Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='snap-y snap-promixity h-screen w-screen overflow-scroll scrollbar-hide'>
        <Navbar />
        <Section id='sec1' color='bg-slate-700'>
          <div className='relative w-full h-full shadow-xl bg-sky-600/10'>
            <div className='absolute w-full h-full translate-y-20 z-10'>
              <div className='flex flex-row justify-center items-center'>
                <div className='flex justify-between py-2 pr-2 pl-10 rounded-full bg-slate-500/25 w-[40%] h-32 backdrop-blur-md shadow-xl'>
                  <div className='flex flex-col justify-center'>
                    <h1
                      className={`${inter.className} text-start font-bold xl:text-3xl lg:text-3xl md:text-2xl text-slate-400`}
                    >
                      Matthew Krain
                    </h1>
                    <h2
                      className={`${inter.className} text-start font-bold xl:text-xl lg:text-xl md:text-md text-sky-300`}
                    >
                      Full Stack Engineer
                    </h2>
                  </div>
                </div>
                <div className='flex xl:w-52 xl:h-52 lg:w-48 lg:h-48 md:w-32 md:h-32 border-2 border-slate-500 rounded-full items-center justify-center shadow bg-slate-800 -translate-x-48 md:-translate-x-20'>
                  <div className='relative w-full h-full rounded-full overflow-hidden grayscale-[25%] shadow-lg'>
                    <Image
                      src='/profile.jpg'
                      alt='profile image'
                      fill
                      priority
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className='absolute bottom-10 right-0 translate-x-[48%] -rotate-45 w-[400%] h-[50%] bg-white backdrop-blur-sm shadow-xl z-0' />
            {/** 
            <div className='xl:block lg:flex w-full h-full z-0'>
              <Image
                className='mx-auto'
                src='/planebuildLG.jpg'
                alt='laptop'
                width={2000}
                height={1000}
                priority
              />
            </div>*/}
            <div
              className={`${inter.className} relative flex w-full justify-center pt-[320px]`}
            >
              <div className='grid grid-cols-3 gap-2'>
                <GridContainer
                  title='About Me'
                  description={[
                    [
                      `Engineer with 3 years of experience in 
                    developing automation software and digital processes for the Chemical
                    Manufacturing industry. Proficient in JavaScript/TypeScript
                    with experience in React and React Native. `,
                    ],
                    [
                      `Adept with working in fast-paced, collaborative environments and continuously
                    seeking new knowledge, particularly in the area of Machine
                    Learning Models. Proven ability to lead technical teams and
                    produce software solutions that yielded multi million-dollar
                    savings for a Fortune 500 company.`,
                    ],

                    [`On a more personal note:`],
                    [
                      `I am a husband, a father of two cats, and a flight enthusiast with a dream to earn my private pilot's license.`,
                    ],
                  ]}
                  span='row-span-2'
                  height='h-[650px]'
                />
                <GridContainer
                  title='Education'
                  description={[
                    [`School`, `Penn State University`],
                    [`Degree`, `Chemical Engineering`],
                    [`Graduation`, ` May 2019`],
                    [`Outcome`, ` Technical problem solver`],
                  ]}
                />
                <GridContainer
                  title='Professional Experience'
                  description={[
                    [
                      `Program automation for standard work processes within SAP ERP.`,
                    ],
                    [
                      `Integrate data sources into PowerBI tools to identify trends, promote decision making, and enhance business intelligence.`,
                    ],
                    [
                      `Digitize standard processes to improve traceability and develop analytics.`,
                    ],
                  ]}
                />
                <GridContainer
                  title='Technical Skills'
                  description={[
                    [
                      `Languages`,
                      ` JavaScript, TypeScript, HTML, CSS, Python, C#, VBA `,
                    ],
                    [
                      `Framework`,
                      ` React, Node.js, Express, TailwindCSS, SST, Jest`,
                    ],
                    [`Databases`, ` MongoDB, MySQL, DynamoDB`],
                    [
                      `Tools`,
                      ` PowerBI, Excel PowerQuery & Macros, AWS, MS Project, Jira, Asana, Git`,
                    ],
                    [
                      `Design Software`,
                      ` Autodesk (Fusion 360 - CAD), Solidworks, MATLAB`,
                    ],
                  ]}
                />
                <GridContainer
                  title='Current Obsession'
                  description={[["..."]]}
                  href='/blog'
                />
              </div>
            </div>
          </div>

          {/*
          <div className='bg-slate-800 w-screen pt-20 pb-10 shadow-lg'>
            
            <div className='m-auto flex w-24 h-24 border-2 rounded-full items-center justify-center shadow'>
              <p className='text-center text-slate-200'>Profile</p>
            </div>
            <h1
              className={`${inter.className} text-center font-bold text-4xl text-slate-300 select-all`}
            >
              Matthew Krain
            </h1>
            <h2
              className={`${inter.className} font-bold text-center text-sky-300`}
            >
              Full Stack Developer
            </h2>
            <p
              className={`${inter.className} text-center text-sm text-slate-400`}
            ></p>
          </div>

          <div className='flex flex-col w-[80%] justify-evenly gap-y-20 p-4'>
            <div className=''>
              <h2 className={`${inter.className}`}>About Me</h2>
              <p className={`${inter.className} text-md text-slate-200`}>
                Full Stack Engineer with 3 years of experience in developing
                automation software and digital processes for the Chemical
                Manufacturing industry. Proficient in JavaScript/TypeScript with
                experience in React and React Native. Adept at working in
                fast-paced, collaborative environments and continuously seeking
                new knowledge, particularly in the area of Machine Learning
                Models. Proven ability to lead technical teams and produce
                software solutions that yield multi million-dollar savings for a
                Fortune 500 company.
              </p>
            </div>
            <div className={`${inter.className}`}>
              <h2>Skills</h2>
              <div className='flex flex-row gap-x-2'>
                <h3
                  className='text-slate-200 underline decoration-2
                '
                >
                  Languages ::
                </h3>
                <p> JavaScript, TypeScript, HTML, CSS, Python, C#, VBA</p>
              </div>
              <div className='flex flex-row gap-x-2'>
                <h3 className='text-slate-200 underline decoration-2'>
                  Framework/Libraries ::
                </h3>
                <p> React, Node.js, Express, TailwindCSS, SST, Jest</p>
              </div>
              <div className='flex flex-row gap-x-2'>
                <h3 className='text-slate-200 underline decoration-2'>
                  Leadership ::
                </h3>
                <p>
                  SAP & Production Team Leader, C.I. Site Leader for Safety and
                  Sustainability, Training Developer/Coordinator
                </p>
              </div>
              <div className='flex flex-row gap-x-2'>
                <h3 className='text-slate-200 underline decoration-2'>
                  Communication ::
                </h3>
                <p>
                  Ecolab Global Sustainability Presenter, Site Safety Trainer
                </p>
              </div>
           </div>
          </div>*/}
        </Section>
        <Section id='sec2' color='bg-slate-700' size='h-min'>
          <div className='relative w-full h-full'>
            <div className='w-full h-full shadow-xl'>
              <div className='w-full pt-20 pb-10 shadow-lg'>
                <h1
                  className={`${inter.className} text-center font-bold text-4xl text-slate-400`}
                >
                  Projects
                </h1>
              </div>
              <ProjectContainer
                title='Knock'
                overview={[
                  `Keep track of your kitchen inventory and find
                            receipes that prevent food waste.`,
                ]}
                keyFeatures={[
                  ` Integrated JSON Web Tokens with Auth0 to improve
                              application security`,
                  `Created a multi-stage aggregation pipeline within
                              MongoDB to delete child branches once parent nodes
                              are deleted`,
                  `Drafted UI with TailwindCSS to increase
                              development speed for custom components`,
                ]}
                techDetails={[
                  `Full Stack MERN Application`,
                  `Auth0 Integration utilizing JSON Web Tokens`,
                  `MongoDB Cloud Services`,
                  `Frontend hosted on Netlify`,
                  `Server hosted on Heroku`,
                ]}
                reverse={false}
              />
              <ProjectContainer
                title='Chuddies'
                overview={[
                  `Keep track of your kitchen inventory and find
                            receipes that prevent food waste.`,
                ]}
                keyFeatures={[
                  ` Integrated JSON Web Tokens with Auth0 to improve
                              application security`,
                  `Created a multi-stage aggregation pipeline within
                              MongoDB to delete child branches once parent nodes
                              are deleted`,
                  `Drafted UI with TailwindCSS to increase
                              development speed for custom components`,
                ]}
                techDetails={[
                  `Full Stack MERN Application`,
                  `Auth0 Integration utilizing JSON Web Tokens`,
                  `MongoDB Cloud Services`,
                  `Frontend hosted on Netlify`,
                  `Server hosted on Heroku`,
                ]}
                reverse={true}
              />
              <ProjectContainer
                title='SAP Automation'
                overview={[
                  `Keep track of your kitchen inventory and find
                            receipes that prevent food waste.`,
                ]}
                keyFeatures={[
                  ` Integrated JSON Web Tokens with Auth0 to improve
                              application security`,
                  `Created a multi-stage aggregation pipeline within
                              MongoDB to delete child branches once parent nodes
                              are deleted`,
                  `Drafted UI with TailwindCSS to increase
                              development speed for custom components`,
                ]}
                techDetails={[
                  `Full Stack MERN Application`,
                  `Auth0 Integration utilizing JSON Web Tokens`,
                  `MongoDB Cloud Services`,
                  `Frontend hosted on Netlify`,
                  `Server hosted on Heroku`,
                ]}
                reverse={false}
              />
            </div>
          </div>
        </Section>
        <Section id='sec3' color='bg-slate-600'>
          <div className='relative w-screen pt-20 pb-10 shadow-lg mb-4'>
            <h1
              className={`${inter.className} text-center font-bold text-4xl text-slate-300`}
            >
              Articles
            </h1>
          </div>
          <div
            className={` ${inter.className} grid grid-cols-2 grid-flow-dense gap-4`}
          >
            <BlogLink
              href='/blog/blogOne'
              date='6/1/2022'
              title='Utilizing MongoDB Aggregate Pipeline to delete child nodes via
                  parent root'
              hashTags={["Nodes", "Aggregation", "MongoDB", "Database"]}
            />
            <BlogLink
              href='/'
              date='6/1/2022'
              title='Creating Dynamically Nested Components'
              hashTags={["Nodes", "FullStack", "Dynamic"]}
            />
            <BlogLink
              href='/'
              date='6/1/2022'
              title='Extracting tabulated data from SAP'
              hashTags={["SAP", "Tables", "Scraping", "Automation"]}
            />
            <BlogLink
              href='/'
              date='6/1/2022'
              title='Checking for rendered element in SAP'
              hashTags={["SAP", "Rendered", "Automation"]}
            />
          </div>
          <div className='-translate-y-40 xl:block lg:flex rotate-90 z-0'>
            <Image
              className='rounded-2xl drop-shadow-lg border-4 border-slate-600'
              src='/planerunway.jpg'
              alt='laptop'
              width={500}
              height={200}
              priority
            />
          </div>
        </Section>

        <Section id='sec4' color='bg-slate-500'>
          <div className='bg-slate-500 w-screen pt-20 pb-10 shadow-lg'>
            <h1
              className={`${inter.className} text-center font-bold text-4xl text-slate-300`}
            >
              Contact Me
            </h1>
          </div>
        </Section>
      </main>
    </>
  );
}
